[package]
name = "bqsp"
version = "0.4.3"
edition = "2021"
authors = ["FssAy"]
readme = "README.md"
license = "CC-BY-4.0"

[features]
default = ["async"]
async = ["tokio"]

[dependencies.tokio]
version = "1.26.0"
optional = true
features = [
    "io-util"
]
